const specialties = [
  `Bipolar`,
  `LGBTQ`,
  `Medication/Prescribing`,
  `Suicide History/Attempts`,
  `General Mental Health (anxiety, depression, stress, grief, life transitions)`,
  `Men's issues`,
  `Relationship Issues (family, friends, couple, etc)`,
  `Trauma & PTSD`,
  `Personality disorders`,
  `Personal growth`,
  `Substance use/abuse`,
  `Pediatrics`,
  `Women's issues (post-partum, infertility, family planning)`,
  `Chronic pain`,
  `Weight loss & nutrition`,
  `Eating disorders`,
  `Diabetic Diet and nutrition`,
  `Coaching (leadership, career, academic and wellness)`,
  `Life coaching`,
  `Obsessive-compulsive disorders`,
  `Neuropsychological evaluations & testing (ADHD testing)`,
  `Attention and Hyperactivity (ADHD)`,
  `Sleep issues`,
  `Schizophrenia and psychotic disorders`,
  `Learning disorders`,
  `Domestic abuse`,
];

const randomSpecialty = () => {
  const random1 = Math.floor(Math.random() * 24);
  const random2 = Math.floor(Math.random() * (24 - random1)) + random1 + 1;

  return [random1, random2];
};

// TODO: Issue #2 spin up actual DB & populate it
const advocateData = [
  {
    city: `New York`,
    degree: `MD`,
    firstName: `John`,
    lastName: `Doe`,
    phoneNumber: 5551234567,
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 10,
  },
  {
    city: `Los Angeles`,
    degree: `PhD`,
    firstName: `Jane`,
    lastName: `Smith`,
    phoneNumber: 5559876543,
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 8,
  },
  {
    city: `Chicago`,
    degree: `MSW`,
    firstName: `Alice`,
    lastName: `Johnson`,
    phoneNumber: 5554567890,
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 5,
  },
  {
    city: `Houston`,
    degree: `MD`,
    firstName: `Michael`,
    lastName: `Brown`,
    phoneNumber: 5556543210,
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 12,
  },
  {
    city: `Phoenix`,
    degree: `PhD`,
    firstName: `Emily`,
    lastName: `Davis`,
    phoneNumber: 5553210987,
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 7,
  },
  {
    city: `Philadelphia`,
    degree: `MSW`,
    firstName: `Chris`,
    lastName: `Martinez`,
    phoneNumber: 5557890123,
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 9,
  },
  {
    city: `San Antonio`,
    degree: `MD`,
    firstName: `Jessica`,
    lastName: `Taylor`,
    phoneNumber: 5554561234,
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 11,
  },
  {
    city: `San Diego`,
    degree: `PhD`,
    firstName: `David`,
    lastName: `Harris`,
    phoneNumber: 5557896543,
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 6,
  },
  {
    city: `Dallas`,
    degree: `MSW`,
    firstName: `Laura`,
    lastName: `Clark`,
    phoneNumber: 5550123456,
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 4,
  },
  {
    city: `San Jose`,
    degree: `MD`,
    firstName: `Daniel`,
    lastName: `Lewis`,
    phoneNumber: 5553217654,
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 13,
  },
  {
    city: `Austin`,
    degree: `PhD`,
    firstName: `Sarah`,
    lastName: `Lee`,
    phoneNumber: 5551238765,
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 10,
  },
  {
    city: `Jacksonville`,
    degree: `MSW`,
    firstName: `James`,
    lastName: `King`,
    phoneNumber: 5556540987,
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 5,
  },
  {
    city: `San Francisco`,
    degree: `MD`,
    firstName: `Megan`,
    lastName: `Green`,
    phoneNumber: 5559873456,
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 14,
  },
  {
    city: `Columbus`,
    degree: `PhD`,
    firstName: `Joshua`,
    lastName: `Walker`,
    phoneNumber: 5556781234,
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 9,
  },
  {
    city: `Fort Worth`,
    degree: `MSW`,
    firstName: `Amanda`,
    lastName: `Hall`,
    phoneNumber: 5559872345,
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 3,
  },
];

export { advocateData };
